package reporter

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/shadowbane/audit-checks/pkg/models"
)

// MarkdownReporter generates Markdown reports
type MarkdownReporter struct{}

// NewMarkdownReporter creates a new MarkdownReporter
func NewMarkdownReporter() *MarkdownReporter {
	return &MarkdownReporter{}
}

// Format returns "markdown"
func (r *MarkdownReporter) Format() string {
	return "markdown"
}

// Extension returns ".md"
func (r *MarkdownReporter) Extension() string {
	return ".md"
}

// templateFuncs contains all template functions
var templateFuncs = template.FuncMap{
	"upper":   strings.ToUpper,
	"title":   strings.Title,
	"default": defaultValue,
	"add":     func(a, b int) int { return a + b },
}

// markdownTemplateStr is the raw template string
const markdownTemplateStr = `# Security Audit Report: {{.AppName}}

**Generated:** {{.GeneratedAt}}
**Auditor:** {{.AuditorType}}
**Path:** {{.AppPath}}

---

## Summary

| Severity | Count |
|----------|-------|
| Critical | {{.Summary.Critical}} |
| High | {{.Summary.High}} |
| Moderate | {{.Summary.Moderate}} |
| Low | {{.Summary.Low}} |
| **Total** | **{{.Summary.Total}}** |

{{if eq .Summary.Total 0}}
No vulnerabilities found.
{{else}}
---

## Vulnerabilities

{{range $i, $v := .Vulnerabilities}}
### {{add $i 1}}. {{$v.PackageName}} - {{$v.Title}} ({{$v.Severity | title}})

| Field | Value |
|-------|-------|
| **Severity** | {{$v.Severity | upper}} |
| **CVE** | {{$v.CVEID | default "N/A"}} |
| **Affected Versions** | {{$v.VulnerableVersions | default "Unknown"}} |
| **Patched Versions** | {{$v.PatchedVersions | default "Unknown"}} |
{{if $v.URL}}| **Reference** | [Link]({{$v.URL}}) |{{end}}

{{if $v.Description}}
**Description:** {{$v.Description}}
{{end}}

{{if $v.Recommendation}}
**Recommendation:** {{$v.Recommendation}}
{{end}}

---

{{end}}
{{end}}

{{if .AIAnalysis}}
## AI Analysis

### Summary

{{.AIAnalysis.Summary}}

{{if .AIAnalysis.Priority}}
### Recommended Fix Order

{{range $i, $pkg := .AIAnalysis.Priority}}
{{add $i 1}}. {{$pkg}}
{{end}}
{{end}}

{{if .AIAnalysis.Remediation}}
### Remediation Commands

` + "```bash" + `
{{range .AIAnalysis.Remediation}}
{{.}}
{{end}}
` + "```" + `
{{end}}

{{if .AIAnalysis.RiskAssessment}}
### Risk Assessment

{{.AIAnalysis.RiskAssessment}}
{{end}}
{{end}}

---

*Generated by Audit Checks*
`

// summaryTemplateStr is the template for summary reports
const summaryTemplateStr = `# Security Audit Summary Report

**Generated:** {{.GeneratedAt}}

---

## Overview

| Metric | Value |
|--------|-------|
| Total Apps Audited | {{.TotalApps}} |
| Apps with Vulnerabilities | {{.AppsWithVulns}} |
| Total Vulnerabilities | {{.TotalVulnerabilities}} |

## Severity Breakdown

| Severity | Count |
|----------|-------|
| Critical | {{.CriticalCount}} |
| High | {{.HighCount}} |
| Moderate | {{.ModerateCount}} |
| Low | {{.LowCount}} |

---

## Per-App Results

{{range .Results}}
### {{.AppName}}

**Auditor:** {{.AuditorType}}

| Severity | Count |
|----------|-------|
| Critical | {{.CriticalCount}} |
| High | {{.HighCount}} |
| Moderate | {{.ModerateCount}} |
| Low | {{.LowCount}} |
| **Total** | **{{.TotalVulnerabilities}}** |

---

{{end}}

*Generated by Audit Checks*
`

// markdownData holds data for the markdown template
type markdownData struct {
	AppName     string
	AppPath     string
	AuditorType string
	GeneratedAt string
	Summary     struct {
		Total    int
		Critical int
		High     int
		Moderate int
		Low      int
	}
	Vulnerabilities []models.Vulnerability
	AIAnalysis      *models.AIAnalysis
}

// Generate creates a Markdown report
func (r *MarkdownReporter) Generate(report *models.Report) ([]byte, error) {
	data := markdownData{
		AppName:         report.AppName,
		AppPath:         report.AppPath,
		AuditorType:     report.AuditorType,
		GeneratedAt:     report.GeneratedAt.Format("2006-01-02 15:04:05 UTC"),
		Vulnerabilities: report.Vulnerabilities,
		AIAnalysis:      report.AIAnalysis,
	}
	data.Summary.Total = report.AuditResult.TotalVulnerabilities
	data.Summary.Critical = report.AuditResult.CriticalCount
	data.Summary.High = report.AuditResult.HighCount
	data.Summary.Moderate = report.AuditResult.ModerateCount
	data.Summary.Low = report.AuditResult.LowCount

	tmpl, err := template.New("markdown").Funcs(templateFuncs).Parse(markdownTemplateStr)
	if err != nil {
		return nil, fmt.Errorf("failed to parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("failed to execute template: %w", err)
	}

	return buf.Bytes(), nil
}

// summaryData holds data for the summary template
type summaryData struct {
	GeneratedAt          string
	TotalApps            int
	AppsWithVulns        int
	TotalVulnerabilities int
	CriticalCount        int
	HighCount            int
	ModerateCount        int
	LowCount             int
	Results              []*models.AuditResult
}

// GenerateSummary creates a summary Markdown report
func (r *MarkdownReporter) GenerateSummary(summary *models.AuditSummary) ([]byte, error) {
	data := summaryData{
		GeneratedAt:          summary.GeneratedAt.Format("2006-01-02 15:04:05 UTC"),
		TotalApps:            summary.TotalApps,
		AppsWithVulns:        summary.AppsWithVulns,
		TotalVulnerabilities: summary.TotalVulnerabilities,
		CriticalCount:        summary.CriticalCount,
		HighCount:            summary.HighCount,
		ModerateCount:        summary.ModerateCount,
		LowCount:             summary.LowCount,
		Results:              summary.Results,
	}

	tmpl, err := template.New("summary").Funcs(templateFuncs).Parse(summaryTemplateStr)
	if err != nil {
		return nil, fmt.Errorf("failed to parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("failed to execute template: %w", err)
	}

	return buf.Bytes(), nil
}

// defaultValue returns the default value if s is empty
func defaultValue(s, def string) string {
	if s == "" {
		return def
	}
	return s
}
